src/Entity/Contacts.php
<?php

namespace App\Entity;

use App\Repository\ContactsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContactsRepository::class)]
class Contacts
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\Column(length: 255)]
    private ?string $Email = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Message = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->Message;
    }

    public function setMessage(string $Message): self
    {
        $this->Message = $Message;

        return $this;
    }
}

templates/admin.html.twig
{% extends 'base.html.twig' %} {% block title %} Admin Panel {% endblock %} {%
block body %}
<div class="container d-flex">
  <div class="card col-6 mx-1">
    <div class="card-header">Contact admin</div>
    <div class="card-body">
      <ul class="list-group">
        {% for contact in contacts %}
        <li class="list-group-item">
          <span
            ><b>{{ contact.id }}</b> {{ contact.name }} (
            {{ contact.email }} )</span
          >
          -
          <a
            href="{{ path('view_contact', { id: contact.id }) }}"
            class="btn btn-primary btn-sm"
            >View message</a
          >
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  <div class="card col-6 mx-1">
    <div class="card-header">Upload your new items</div>
    <form
      class="card-body"
      method="post"
      action=""
      enctype="multipart/form-data"
    >
      Title:<br />
      <input class="form-control" type="text" name="title" required /><br />
      description:<br />
      <input
        class="form-control"
        type="text"
        name="description"
        required
      /><br />
      Price:<br />
      <input class="form-control" name="price" required /><br />
      Quantity: <br />
      <input class="form-control" name="quantity" required /><br />
      Photo:<br />
      <input class="form-control" type="file" name="photo" /><br />
      <input class="btn btn-primary" type="submit" name="save" value="Submit" />
      {% if error is defined and error is not empty %}
      <div class="alert alert-danger">
        {{ error }}
      </div>
      {% endif %}
    </form>
  </div>
</div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Nunito&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="/node_modules/bootstrap/dist/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="/style.css" />
  </head>
  <body class="bg-black">
    <header class="container col d-flex my-5">
      <nav class="navbar navbar-expand-lg navbar-dark bg-black">
        <div class="container my-3 w-25">
          <h1>
            <a href="/"
              ><img class="w-100 h-100" src="/images/logo-main.jpg" />
            </a>
          </h1>
        </div>
        <div class="container-fluid my-3 w-75">
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div
            class="collapse navbar-collapse justify-content-evenly"
            id="navbarSupportedContent"
          >
            <ul class="navbar-nav">
              <li class="nav-item">
                <a
                  class="nav-link active text-primary"
                  aria-current="page"
                  href="my-services"
                  >My services</a
                >
              </li>
              <li class="nav-item">
                <a
                  class="nav-link active text-primary"
                  aria-current="page"
                  href="eyelashes"
                  >Eyelashes</a
                >
              </li>
              <li class="nav-item">
                <a
                  class="nav-link active text-primary"
                  aria-current="page"
                  href="about-me"
                  >About me</a
                >
              </li>
              <li class="nav-item">
                <a
                  class="nav-link active text-primary"
                  aria-current="page"
                  href="contacts"
                  >Contact me</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link active text-primary" href="my-shop"
                  >My shop</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link active text-primary" href="my-cart"
                  >My Cart</a
                >
              </li>
              <li class="nav-item dropdown"></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    {% block body %} {% endblock %}

    <footer class="container col d-flex my-5">
      <div
        class="row col-6 justify-content-start align-items-center text-primary"
      >
        <img class="w-25" src="/images/logo-main.jpg" />
      </div>
      <div class="row col-6 text-end align-items-end text-primary">
        <p>All rights reserved, 2022</p>
      </div>
    </footer>

    <script src="/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

templates/bodyaboutme.html.twig
{% extends 'base.html.twig' %} {% block title %} About me {% endblock %} {%
block body %}
<section class="container col d-flex my-5" id="about-me">
  <div class="card bg-black text-primary w-50 px-2">
    <h1>About Me</h1>
    <img src="images/profile1.jpg" class="card-img-top" alt="..." />
  </div>
  <div
    class="container card-body w-50 text-primary px-2 d-flex align-items-center"
  >
    <div class="container">
      <h5 class="card-title px-2">BenSen Rasa</h5>
      <p class="card-text px-2">
        As vardu Rasa, sukuriau savo eyelashes linija. As vardu Rasa, sukuriau
        savo eyelashes linija.As vardu Rasa, sukuriau savo eyelashes linija.As
        vardu Rasa, sukuriau savo eyelashes linija.As vardu Rasa, sukuriau savo
        eyelashes linija.
      </p>
    </div>
  </div>
</section>
{% endblock %}

templates/bodycontacts.html.twig
{% extends 'base.html.twig' %} {% block title %} Contacts {% endblock %} {%
block body %}
<div class="container px-2 text-primary">
  <h1 class="h1-responsive font-weight-bold my-4">Contact me</h1>
  <p class="text-center w-responsive mx-auto mb-5">
    Do you have any questions? Please do not hesitate to contact me directly.
  </p>
  <div class="row">
    <div class="col-md-9 mb-md-0 mb-5">
      <form action="{{ path('contacts') }}" method="post">
        <div class="row">
          <div class="col-md-6">
            <div class="md-form mb-0">
              <input name="client-name" class="form-control" value="{{formValues.clientName|default("")

              }}" required/>
              <label>Your name</label>
            </div>
          </div>
          <div class="col-md-6">
            <div class="md-form mb-0">
              <input name="client-email" class="form-control" value="{{formValues.clientEmail|default("")

              }}"/>
              <label>Your email</label>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="md-form">
              <textarea
                name="client-message"
                class="form-control md-textarea"
                >{{formValues.clientMessage|default("")}}</textarea
              >
              <label>Your message</label>
            </div>
          </div>
        </div>

        <div class="text-center text-md-left">
          <input type="submit" class="btn btn-primary" value="Submit" />
        </div>
      </form>
      {% if error is defined and error is not empty %}
      <div class="alert alert-danger">
        {{ error }}
      </div>
      {% endif %}
    </div>
    <div class="col-md-3 text-center">
      <ul class="list-unstyled mb-0">
        <li>
          <i class="fas fa-map-marker-alt fa-2x"></i>
          <p>
            Post code NN48DL , St Leonards Road, Northampton , Northamptonshare
          </p>
        </li>
        <li>
          <i class="fas fa-phone mt-4 fa-2x"></i>
          <p>+44 7728 550909</p>
        </li>
        <li>
          <i class="fas fa-envelope mt-4 fa-2x"></i>
          <p>rasa.pociute123@gmail.com</p>
        </li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

templates/bodyeyelashes.html.twig
{% extends 'base.html.twig' %} {% block title %} Eyelashes {% endblock %} {%
block body %}
<section class="container col d-flex my-5" id="eyelashes">
  <div class="container col-md-6 px-2">
    <h1 class="text-primary">Eyelashes</h1>
    <p class="text-primary">
      Here you can check my created eyelashes. The list of eyelashes types,
      curve type size and I provide: C curl 0,07 the size you can choose: 7, 8,
      9, 10, 11, 12, 13, 14, MIX. D curl 0,07 the size you can choose: 7, 8, 9,
      10, 11, 12, 13, 14, MIX. M curl 0,07 the size you can choose: 7, 8, 9, 10,
      11, 12, 13, 14, MIX. O curl 0,07 the size you can choose: 7, 8, 9, 10, 11,
      12, 13, 14, MIX. C curl 0,10 the size you can choose: 7, 8, 9, 10, 11, 12,
      13, 14, MIX. D curl 0,10 the size you can choose: 7, 8, 9, 10, 11, 12, 13,
      14, MIX. M curl 0,10 the size you can choose: 7, 8, 9, 10, 11, 12, 13, 14,
      MIX. O curl 0,10 the size you can choose: 7, 8, 9, 10, 11, 12, 13, 14,
      MIX.
    </p>
  </div>

  <div
    id="carouselExampleCaptions"
    class="carousel slide px-2 col-md-6"
    data-bs-ride="false"
  >
    <div class="carousel-indicators">
      <button
        type="button"
        data-bs-target="#carouselExampleCaptions"
        data-bs-slide-to="0"
        class="active"
        aria-current="true"
        aria-label="Slide 1"
      ></button>
      <button
        type="button"
        data-bs-target="#carouselExampleCaptions"
        data-bs-slide-to="1"
        aria-label="Slide 2"
      ></button>
      <button
        type="button"
        data-bs-target="#carouselExampleCaptions"
        data-bs-slide-to="2"
        aria-label="Slide 3"
      ></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="photo/photo-1.jpg" class="img-fluid rounded" alt="..." />
        <div class="carousel-caption text-black d-none d-md-block">
          <h5>0.07mm</h5>
          <p>The size of eyelashes</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="photo/photo-2.jpg" class="img-fluid rounded" alt="..." />
        <div class="carousel-caption text-black d-none d-md-block">
          <h5>12mm</h5>
          <p>The size of eyelashes</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="photo/photo-3.jpg" class="img-fluid rounded" alt="..." />
        <div class="carousel-caption text-black d-none d-md-block">
          <h5>M type eyelashes</h5>
          <p>Whole box</p>
        </div>
      </div>
    </div>
    <button
      class="carousel-control-prev text-"
      type="button"
      data-bs-target="#carouselExampleCaptions"
      data-bs-slide="prev"
    >
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button
      class="carousel-control-next text-"
      type="button"
      data-bs-target="#carouselExampleCaptions"
      data-bs-slide="next"
    >
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</section>
{% endblock %}

templates/bodymyservices.html.twig
{% extends 'base.html.twig' %} {% block title %} My services {% endblock %} {%
block body %}

<section class="container col my-5" id="my-services">
  <div class="row text-primary">
    <h1>My Services</h1>
    <iframe
      src="https://book.heygoldie.com/BenSen-lashes"
      width="1000"
      height="800"
      style="border: 0"
      allowfullscreen=""
      loading="lazy"
      referrerpolicy="no-refferer-when-downgrade"
    ></iframe>
  </div>
</section>

{% endblock %}

templates/mycart.html.twig
{% extends 'base.html.twig' %}{% block title %} My Cart {% endblock %} {% block
body %}
<div class="container col my-5">
  <div class="row bg-black text-primary container">
    <div class="col-3">
      <div class="card h-75 bg-black border-light text-center">
        <img
          class="h-50 w-50 px-1 py-1 rounded"
          {#
          src="data:{{-----}};base64,{{ ----}}"
          #}
          alt=".."
        />
        <div class="card-body">
          <h3 class="card-title">----</h3>
          <p>---</p>
          <p>Price:<b>---- </b></p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/myshop.html.twig
{% extends 'base.html.twig' %}{% block title %} E-Shop {% endblock %} {% block
body %}
<div class="container col my-2">
  <div class="row col-sx-1 bg-black">
    {% for item in items %}
    <div class="col-3 bg-black border-light text-center my-2">
      <div class="card h-100">
        <img
          class="h-50 w-50 px-1 py-1 rounded"
          src="data:{{ item.type }};base64,{{ item.photoString }}"
          alt=".."
        />
        <div class="card-body">
          <h3 class="card-title">{{ item.title }}</h3>
          <p>{{ item.description }}</p>
          <p>
            Price:<b> {{ item.price }} </b>
          </p>
          <input class="btn btn-primary" name="AddToCart" type="submit" />
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/single-contact.html.twig
{% extends 'base.html.twig' %} {% block title %} View contact {% endblock %} {%
block body %}
<div class="card container">
  <div class="card-header">View contact - {{ contact.id }}</div>
  <div class="card-body">
    <ul class="list-group">
      Contact name:
      <b>{{ contact.name }}</b>
      Contact email:
      <b>{{ contact.email }}</b>
      Message:
      <code>{{ contact.message }}</code>
    </ul>
  </div>
  <div class="card-footer">
    <a href="{{ path('admin') }}">Back to admin page</a>
  </div>
</div>
{% endblock %}